### ISSUE TITLE
fedfv运行报错

### ISSUE THREAD

**Issue by Jiaxiangren** [WwZzz/easyFL#10]
您好，我用了以下代码
python main.py --task mnist_classification_cnum100_dist0_skew0_seed0 --model cnn --algorithm fedfv --num_rounds 3 --num_epochs 1 --learning_rate 0.215 --proportion 0.1 --batch_size 10 --eval_interval 1
遇到报错
![image](https://user-images.githubusercontent.com/31751000/166342505-18067d88-fc30-401a-81a4-5705c620e4c1.png)
请问如何修复这个bug？ 十分感谢！

**Comment by WwZzz** [comment]
您好，感谢指出bug。bug的原因是因为，前几天把server.communicate的结果改成python的dict类型返回，忘了把fedfv的相应部分改过来了。以及Benchmark.TaskCalculator.test的返回形式也改成了dict，下面还会有一处报错。修复bug要改2处代码，分别位于fedfv文件中server.iterate函数：34,35行以及client.reply函数的80行，我已修复并上传github。

2022-05-03 07:34:20 "jzrzy" ***@***.***> 写道：

您好，我用了以下代码
python main.py --task mnist_classification_cnum100_dist0_skew0_seed0 --model cnn --algorithm fedfv --num_rounds 3 --num_epochs 1 --learning_rate 0.215 --proportion 0.1 --batch_size 10 --eval_interval 1
遇到报错

请问如何修复这个bug？ 十分感谢！

**Comment by Jiaxiangren** [comment]
十分感谢！
