### ISSUE TITLE
一个小小的问题，fflow.py中read_option函数的gpu参数应该是list之类的可迭代的，而不是int型。

### ISSUE THREAD

**Issue by ccccczzzzasd** [WwZzz/easyFL#20]
RT

**Comment by WwZzz** [comment]
你好，旧版本easyFL里的read_option参数主要从命令行读取，输入形式是在命令行中加入参数--gpu 0 1 2字样，以空格分隔，将会被默认处理成数组；
新版本在分支flgo中，输入的参数字典gpu参数会自动转化类型，既可以输入{'gpu':0}，也可以输入{'gpu':[0]}。
转化的代码在fflow.init的304-316行，根据read_option_from_command中设置的默认类型转换。

**Comment by ccccczzzzasd** [comment]
感谢回复
