### ISSUE TITLE
fmodule.py文件

### ISSUE THREAD

**Issue by QQQiSeven** [WwZzz/easyFL#8]
您好，看到您最近在更新代码，刚刚发现fmodule.py里第90行出现的lossfunc好像没有初始化？冒昧打扰了

**Comment by WwZzz** [comment]
你好，近期修改中对于给定数据集的任务，把evaluation的部分封装给该数据集的TaskCalculator完成，具体路径在benchmark/数据集名称/core.py中。目前这个fmodule中的test函数被弃用了，还没有删除，谢谢你的提醒。​

**Comment by QQQiSeven** [comment]
哦哦，那能不能问一下整个修改最近会结束吗？因为最近想用您的框架试试自己的算法😊  觉得您的代码写的太好啦！（虽然还是读代码中😛-------- 原始邮件 --------发件人： WwZzz ***@***.***>日期： 2021年12月23日周四 23:40收件人： WwZzz/easyFL ***@***.***>抄送： QQQiSeven ***@***.***>, State change ***@***.***>主    题： Re: [WwZzz/easyFL] fmodule.py文件 (Issue #8)

你好，近期修改中对于给定数据集的任务，把evaluation的部分封装给该数据集的TaskCalculator完成，具体路径在benchmark/数据集名称/core.py中。目前这个fmodule中的test函数被弃用了，还没有删除，谢谢你的提醒。​

**Comment by WwZzz** [comment]
> 哦哦，那能不能问一下整个修改最近会结束吗？因为最近想用您的框架试试自己的算法😊  觉得您的代码写的太好啦！（虽然还是读代码中😛-------- 原始邮件 --------发件人： WwZzz ***@***.***>日期： 2021年12月23日周四 23:40收件人： WwZzz/easyFL ***@***.***>抄送： QQQiSeven ***@***.***>, State change ***@***.***>主 题： Re: [WwZzz/easyFL] fmodule.py文件 (Issue #8) 你好，近期修改中对于给定数据集的任务，把evaluation的部分封装给该数据集的TaskCalculator完成，具体路径在benchmark/数据集名称/core.py中。目前这个fmodule中的test函数被弃用了，还没有删除，谢谢你的提醒。​—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

谢谢，不过目前还没有完全测试好，跑通大部分情形是可以的，但有些地方可能有bug，近期还在逐一测试。
